name: Daily Lofi Maker

on:
  schedule:
    - cron: '0 0 * * *' # 매일 UTC 0시 (한국시간 오전 9시) 실행
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # [중요] Node.js 최신 버전 설치 (자바스크립트 엔진 경고 해결)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg ghostscript imagemagick
        # ImageMagick 정책 수정
        sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml
        pip install -r requirements.txt

    # [핵심] 등록한 쿠키 Secret을 실제 파일(cookies.txt)로 만듦
    - name: Create Cookie File
      run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

    - name: Run Automation Script
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        SHEET_URL: ${{ secrets.SHEET_URL }}
      run: python main.py
